spring:
  error:
    whitelabel:
      enabled: false
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mapping: false
  application: RoleWorldServer
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:hsql://localhost/xdb
    username: SA
    password:
    h2:
      console:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.HSQLDialect
    generate-ddl: true
    show-sql: false